set PORT=8080
set BODY_LIMIT=5mb
set ALLOW_CORS_ORIGIN=*
set ALLOW_CORS_METHODS=OPTIONS,GET,POST,PUT,PATCH,DELETE

set MONGO_DB_NAME=simpliclarify-staging
set MONGO_HOSTS=cluster0.ceuwydz.mongodb.net
set MONGO_USERNAME=singhiharsh
set MONGO_PASSWORD=simpliclarify
set IS_MONGO_CREDENTIALS=true
set MONGO_REPLICASET=rs0
set MONGO_READ_PREFERENCE=secondaryPreferred

set SERVICE_NAME=SIMPLICLARIFY 

set KEY_ID=rzp_test_aEhY7GaQkj19oy
set KEY_SECRET=IvHHE8ysM12Ethwm19EImhgy
set RAZORPAYX_KEYID=1234
set RAZORPAYX_KEYSECRET=1234
set ALLOW_PAYOUTS=1234
set RAZORPAYX_ACCOUNT_NUMBER=1234
npm run dev